from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet


def generate_pdf(trip, filename):

    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph(
            trip["title"],
            styles["Title"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    content.append(
        Paragraph(
            trip["overview"],
            styles["BodyText"]
        )
    )

    content.append(
        Spacer(1, 20)
    )

    for day in trip["days"]:

        content.append(
            Paragraph(
                day["day"],
                styles["Heading2"]
            )
        )

        for activity in day["activities"]:

            content.append(
                Paragraph(
                    f"• {activity}",
                    styles["BodyText"]
                )
            )

        content.append(
            Spacer(1, 10)
        )

    content.append(
        Paragraph(
            f"Hotel: {trip['hotel']}",
            styles["Heading3"]
        )
    )

    content.append(
        Paragraph(
            f"Food: {trip['food']}",
            styles["Heading3"]
        )
    )

    content.append(
        Paragraph(
            f"Transport: {trip['transport']}",
            styles["Heading3"]
        )
    )

    content.append(
        Paragraph(
            f"Budget: {trip['budget']}",
            styles["Heading3"]
        )
    )

    pdf.build(content)



# from reportlab.platypus import (
#     SimpleDocTemplate,
#     Paragraph,
#     Spacer,
#     Table,
#     TableStyle,
#     PageBreak
# )

# from reportlab.lib import colors

# from reportlab.lib.styles import (
#     getSampleStyleSheet,
#     ParagraphStyle
# )

# from reportlab.lib.enums import TA_CENTER


# def add_footer(canvas, doc):

#     canvas.saveState()

#     canvas.setFont(
#         "Helvetica",
#         9
#     )

#     canvas.setFillColor(colors.grey)

#     canvas.drawString(
#         40,
#         30,
#         "Generated by AI Travel Planner"
#     )

#     canvas.drawRightString(
#         550,
#         30,
#         f"Page {doc.page}"
#     )

#     canvas.restoreState()


# def generate_pdf(trip, filename):

#     pdf = SimpleDocTemplate(filename)

#     styles = getSampleStyleSheet()

#     title_style = ParagraphStyle(
#         "TitleStyle",
#         parent=styles["Title"],
#         textColor=colors.HexColor("#4F46E5"),
#         alignment=TA_CENTER
#     )

#     subtitle_style = ParagraphStyle(
#         "Subtitle",
#         parent=styles["Heading2"],
#         textColor=colors.HexColor("#2563EB")
#     )

#     section_style = ParagraphStyle(
#         "Section",
#         parent=styles["Heading3"],
#         textColor=colors.HexColor("#7C3AED")
#     )

#     normal_style = styles["BodyText"]

#     content = []

#     # Header

#     content.append(
#         Paragraph(
#             "✈ AI Travel Planner",
#             title_style
#         )
#     )

#     content.append(
#         Spacer(1, 10)
#     )

#     content.append(
#         Paragraph(
#             trip["title"],
#             subtitle_style
#         )
#     )

#     content.append(
#         Spacer(1, 20)
#     )

#     content.append(
#         Paragraph(
#             trip["overview"],
#             normal_style
#         )
#     )

#     content.append(
#         Spacer(1, 25)
#     )

#     # Day-wise itinerary

#     content.append(
#         Paragraph(
#             "📅 Day-wise Itinerary",
#             subtitle_style
#         )
#     )

#     content.append(
#         Spacer(1, 15)
#     )

#     for day in trip["days"]:

#         content.append(
#             Paragraph(
#                 day["day"],
#                 section_style
#             )
#         )

#         content.append(
#             Spacer(1, 5)
#         )

#         for activity in day["activities"]:

#             content.append(
#                 Paragraph(
#                     f"• {activity}",
#                     normal_style
#                 )
#             )

#         content.append(
#             Spacer(1, 15)
#         )

#     # Travel Information

#     content.append(
#         Spacer(1, 10)
#     )

#     content.append(
#         Paragraph(
#             "🌍 Travel Information",
#             subtitle_style
#         )
#     )

#     content.append(
#         Spacer(1, 10)
#     )

#     info_table = Table([
#         ["Category", "Details"],
#         ["🏨 Hotel", trip["hotel"]],
#         ["🍽 Food", trip["food"]],
#         ["🚕 Transport", trip["transport"]],
#         ["💰 Budget", trip["budget"]]
#     ])

#     info_table.setStyle(
#         TableStyle([

#             (
#                 "BACKGROUND",
#                 (0, 0),
#                 (-1, 0),
#                 colors.HexColor("#4F46E5")
#             ),

#             (
#                 "TEXTCOLOR",
#                 (0, 0),
#                 (-1, 0),
#                 colors.white
#             ),

#             (
#                 "FONTNAME",
#                 (0, 0),
#                 (-1, 0),
#                 "Helvetica-Bold"
#             ),

#             (
#                 "GRID",
#                 (0, 0),
#                 (-1, -1),
#                 1,
#                 colors.black
#             ),

#             (
#                 "ROWBACKGROUNDS",
#                 (0, 1),
#                 (-1, -1),
#                 [
#                     colors.whitesmoke,
#                     colors.lightgrey
#                 ]
#             ),

#             (
#                 "FONTSIZE",
#                 (0, 0),
#                 (-1, -1),
#                 10
#             )
#         ])
#     )

#     content.append(
#         info_table
#     )

#     content.append(
#         Spacer(1, 25)
#     )

#     # Thank You Section

#     content.append(
#         Paragraph(
#             "✨ Have a wonderful journey!",
#             subtitle_style
#         )
#     )

#     content.append(
#         Spacer(1, 10)
#     )

#     content.append(
#         Paragraph(
#             "This itinerary was generated using AI Travel Planner.",
#             normal_style
#         )
#     )

#     pdf.build(
#         content,
#         onFirstPage=add_footer,
#         onLaterPages=add_footer
#     )